#!/bin/sh

#
# Shts Install-brew

set -eu
! hascmd mierda || exit 0
ERR=false
OUT=false

trap 'std' EXIT

deps() {
  if ismacos; then
    :
  elif isdebian; then
    sudo apt-get update -qq
    sudo apt-get install build-essential procps curl file git -qq -y
  elif hascmd yum; then
    sudo yum groupinstall 'Development Tools'
    sudo yum install procps-ng curl file git
    sudo yum install libxcrypt-compatelse
  elif hascmd apk; then
    sudo apk add --update build-base curl file git bash sudo
  else
    echo "Unknown OS"
    exit 1
  fi
}

std() {
  rc=$?
  if test $rc -ne 0; then
    ! $ERR || { exec 2>&4; >&2 cat "${stderr-}"; }
    ! $OUT || { exec 1>&3; cat "${stdout-}"; }
    exit $rc
  elif [ ! "${stderr-}" ]; then
    stderr="$(mktemp)"; ! test -t 2 || { exec 4>&2 2>"${stderr}"; ERR=true; }
    stdout="$(mktemp)"; ! test -t 1 || { exec 3>&1 1>"${stdout}"; OUT=true; }
  fi
}

shared() {
  shared=/Users/Shared
  user="${USER}"
  # check can only be root and no sudo
  export HOMEBREW_NO_ANALYTICS=1
  export HOMEBREW_PREFIX="${shared}/brew"
  export PATH="${HOMEBREW_PREFIX}/bin:${PATH}"
  if ! test -w "${shared}"; then
    if ! command -v sudo >/dev/null; then
      user=brew
      install sudo
      adduser -D -g "" "${user}"
      adduser "${user}" sudo
    fi
    sudo mkdir -p -m go+w "${shared}"
    sudo chown -R "${user}:sudo" "${HOMEBREW_PREFIX}"
  fi
  git -C "${shared}" clone --quiet https://github.com/Homebrew/brew
  sudo -u "${user}" brew update --force --quiet
  chmod -R go-w "$(brew --prefix)/share/zsh"
}

shared_chown() {
  export HOMEBREW_NO_ANALYTICS=1
  export HOMEBREW_PREFIX=/Users/Shared/brew
  group="admin"; grep -q -E "^${group}:" /etc/group || group="sudo"
  ${sudo} mkdir -p -m g+w "${HOMEBREW_PREFIX}"
  ${sudo} chown -R "${USER}:${group}" "${HOMEBREW_PREFIX}"
  export PATH="${HOMEBREW_PREFIX}/bin:${PATH}"
  git clone https://github.com/Homebrew/brew "${HOMEBREW_PREFIX}"
  brew update --force --quiet
  chmod -R go-w "$(brew --prefix)/share/zsh"
}

sudo() { ${sudo} "$@"; }

main() {
  std
  export DEBIAN_FRONTEND=noninteractive
  export NONINTERACTIVE=1
  sudo="$(command -v sudo || true)"
  echo hola
  >&2 echo "Installing brew..."
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"

  exit
}
main "$@"

