#!/bin/bash

export JETBRAINS="${HOME}/JetBrains"
config="${JETBRAINS}/config/PyCharm"
export PYCHARM_PROPERTIES="${config}/.properties"
export PYCHARM_VM_OPTIONS="${config}/.vmoptions"

root="${HOME}/binsh"
export PATH="${root}/bin:${PATH}"
nohup /Applications/PyCharm.app/Contents/MacOS/pycharm "${root}" &>/tmp/pycharm_binsh.out
