#!/bin/bash

PROJECT_DIR="$(dirname "${0%.*}")"; export PROJECT_DIR
PATH="$(brew --prefix ruby)/bin:${PROJECT_DIR}/bin:${PATH}"; export PATH
contents=/Applications/PyCharm.app/Contents
jedi="${contents}/plugins/terminal/jediterm-bash.in"
line="source /etc/profile"
test "$(cat "${jedi}")" = "${line}" || { mv "${jedi}" "${jedi}.bak" && echo "${line}" >> "${jedi}"; }

"${contents}/MacOS/pycharm" "${PROJECT_DIR}"
