#!/bin/sh

: git branch

set -eu

PATH="$(cd "$(dirname "$0")"; pwd -P):${PATH}"

#######################################
# display local branches
# Arguments:
#   None
#######################################
git branch --format='%(refname:short)' "$@"
